### PR TITLE
Added raw mouse button input

### PR DESCRIPTION
**Pull request by Elektroney**
Thanks for your kind and fast response im having a bit of trouble with github so i had to create a new pullrequest!
If you were to accept this pullrequest would you be so kind and close the issue #19.
He posted this issue on a bounty hunting site so i can get rewarded! ^^

### CODE REVIEW

**Comment by Elringus** [comment]
Ok, so I've tried testing like this:

```cs
RawMouseButtons.Start(WorkInBackground);
RawMouseButtons.OnMouseUp += LogKeyUp;
RawMouseButtons.OnMouseDown += LogKeyDown;
```

But it doesn't seem to work. Eg, when I click LMB it logs key up twice.

Also, please format and clean the code and try to follow the style used in the other files.

**Comment by Elringus** [comment]
Thank you for the cleanup! I've also refactored it a bit. While it's working for mouse buttons now, I've noticed that when `Work In Background` is enabled and Unity editor window is out of focus, mouse is unusable (cursor moves very slow and becomes unresponsive). I've tried running the hooks in a background thread (`Async` option), but wasn't able to make it work. Do you have any ideas?

**Comment by Elektroney** [comment]
It probably has todo with the thread id, of th hook or the hook id. we maybe instead of hooking all processes only should hook the visible ones may e there is some interference or something ill tst it once im back home

**Comment by Elringus** [comment]
Sorry, but judging by the above 3 commits it doesn't look like you understand what you're doing. Both keyboard and mouse detection was working correctly, but you just broke it with changes that doesn't make any sense. I'll have to close this PR, as I can't spend more time on this. Working version before the 3 changes is in https://github.com/Elringus/UnityRawInput/tree/feat/mouse (in case anyone would like to suggest a fix for the slow cursor)

**Pull request closed without merging**
