### PR TITLE
Expand Functionality

### PR DESCRIPTION
**Pull request by Repiteo**
- RawKey from enum to struct, expands RawKey functionality to ScanCodes if polling background input
- BUG: Unity for some reason won't recognize upper byte of scancode. Not sure if this is a bug with Unity itself or the way the hook is being called, but there's a temporary workaround in place
- Can now arbitrarily call for and create rawkeys based on string inputs, comprable to AutoHotKey's implementation
- RawInput given ToString() functionality, outputting the currently pressed keys as a string hash
- LogRawInput now displays currently pressed keys in playmode using the above
- Added asmdef, only include Windows/Editor

### CODE REVIEW

**Comment by Elringus** [comment]
Thanks for the PR! 

On the first glance, I've noticed some formatting changes, which pollute the diff, such as: 
https://github.com/Elringus/UnityRawInput/pull/26/files#diff-d5f75388685dc03f35df3bcfff6b89afb64e8c1ee4c2cf5c1f6ee113e3186437L10
https://github.com/Elringus/UnityRawInput/pull/26/files#diff-926963e7918df2407b870efd237621396acf69c9aad81d2d5b228b23e2711462L15
https://github.com/Elringus/UnityRawInput/pull/26/files#diff-c16ebd25298340efa683ac264c57688c50d3e3a1a3e1978c5d965a060b4d0a8aL127 
— please clean them out, sot it's easier to read. 

The new struct contains a lot of stuff, is it really necessary? Can you please clarify the use cases for this and why it can't be implemented via existing enum?

**Comment by Repiteo** [comment]
Ahh, my editor must've added those, hopefully it'll be straightforward to revert

The struct indeed contains quite a bit, but the main thing it contributes is the ability to send keys that don't have an associated Virtual Key but **do** have a detectable ScanCode. Three notable instances added are the uncommon "international" keys
https://github.com/Elringus/UnityRawInput/pull/26/files#diff-bab5e8dbcc406b7dbbd4e05f41420ff8a4393c3b525e1dafc3c793ac9541f87fL1143

The main addition to the struct is an additional function that checks for string inputs (like from a config file). It can parse this input and compare it to several common names for keys and assign an appropriate key as necessary. But if nothing matches, it can then try to match against the syntax `vk##`, `sc###`, or `vk##sc###` (lifted from [AutoHotkey](https://lexikos.github.io/v2/docs/commands/Send.htm#vk)) to either assign or send unique key combinations not strictly tied to the standard key formats

Going to a struct also necessitated other changes in validating if a given key matches against another key, which accounts for the final bulk of additions. I considered changing to a partial struct to spread the code across multiple files, but ultimately went with the one file. If you think it'd be better spread across files then I can do that instead!

**Comment by Elringus** [comment]
Thank you for the clarification! Not sure if few uncommon keys support justify 1k+ lines of code, implicit conversions complexity and breaking changes. String parsing/matching looks like a nice feature, but I feel it's a bit too specific/opinionated and would be better off as a separate solution. That said, the PR contains a lot of useful info and some improvements I'd like to merge, so I'll keep it open for now and will get back at it later. Thank you for the effort!

**Comment by Repiteo** [comment]
Hmm, thats a good point about an alternative solution, didn't really consider that; this would probably be better as a separate implementation which complimented the existing RawKey format

Feel free to take whatever from this you want, but I'll probably try my hand a different implementation. Not sure when that'll be though

**Pull request closed without merging**
